### ISSUE TITLE
Remove Nth node from end of List

### ISSUE THREAD

**Issue by Faraaz22** [Chitresh-code/DSA_Worksheet#7]
Kindly assign this to me under hacktober fest.

**Problem**
Given the head of a linked list, remove the nth node from the end of the list and return its head.

Example 1:

```
Input: head = [1,2,3,4,5], n = 2
Output:[1,2,3,5]
```

Example 2:

```
Input: head = [1], n = 1
Output: []
```

Example 3:

```
Input: head = [1,2], n = 1
Output: [1]
```

**Constraints:**

 ```
The number of nodes in the list is sz.
 1 <= sz <= 30
 0 <= Node.val <= 100
 1 <= n <= sz
```

**Comment by yanurag1414** [comment]
Assign this work to me.

**Comment by Chitresh-code** [comment]
Done @yanurag1414 Happy Coding!

**Comment by gitaditee** [comment]
please assign this task to me

**Comment by y9rabbito** [comment]
Try to solve it in optimise way in real world scenarion it will take linear time O(n) to execute the code. 
Try to check if its the last node or the only node then delete and return null;
Otherwise just swap Nth Node and N+1 Node values then delete N+1 node values Complexity - O(1) Constant time in apriori analysis.

**Comment by gitaditee** [comment]
Ok sure @y9rabbito

**Comment by gitaditee** [comment]
@y9rabbito can you check the solution and let me know if any changes are required
